# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9ac032c000555412da037a527d6e2df794e348fe5184a3e68ab9ed25f3a228bacdc192f2ab5157e0f0911d2e6b518759f8d3349d817ee3eb3738a4c6bb0cd2b
  google_client_id: 737532929115-to2smqf9g9fqcm0ggiqm75lnua2neour.apps.googleusercontent.com
  google_client_secret: iRx26oi9KzuzKw3IYt9Y2WGN

test:
  secret_key_base: 0bbc0b41000e83ef2b91acd76166fdd238d0153d2c6ac54c2b4202f923affc697f7888c819c0d392dc5c4074b1410bf4f55a579a58cd0cd92240b5ba424b17b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
